name: Clean up old workflow execution records
on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days to retain runtime records for each workflow'
        required: true
        default: '7'
        type: string
      minimum_runs:
        description: 'Minimum number of runs to retain for each workflow'
        required: true
        default: '6'
        type: string
      delete_workflow_pattern:
        description: 'The workflow name or file name to be cleaned (If not set, it applies to all workflows.)'
        required: false
        type: string
      delete_workflow_by_state_pattern:
        description: 'Filter by workflow status: active, deleted, disabled_fork, disabled_inactivity, disabled_manually'
        required: false
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - active
          - deleted
          - disabled_inactivity
          - disabled_manually
      delete_run_by_conclusion_pattern:
        description: 'Remove running records based on running conclusions.: action_required, cancelled, failure, skipped, success'
        required: false
        default: "ALL"
        type: choice
        options:
          - "ALL"
          - "Unsuccessful: action_required,cancelled,failure,skipped"
          - action_required
          - cancelled
          - failure
          - skipped
          - success
      dry_run:
        description: 'Record simulated changes, but do not perform actual deletion operations.'
        required: false
        default: false
        type: boolean

jobs:
  cleanup_workflow_runs:
    name: Delete old workflow run records jobs
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: 运行 Mattraks 删除工作流运行记录操作
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event_name == 'schedule' && 0 || github.event.inputs.days }}
          keep_minimum_runs: ${{ github.event_name == 'schedule' && 5 || github.event.inputs.minimum_runs }}
          delete_workflow_pattern: ${{ github.event_name == 'schedule' && '' || github.event.inputs.delete_workflow_pattern }}
          delete_workflow_by_state_pattern: ${{ github.event_name == 'schedule' && 'ALL' || github.event.inputs.delete_workflow_by_state_pattern }}
          delete_run_by_conclusion_pattern: ${{ github.event_name == 'schedule' && 'ALL' || (startsWith(github.event.inputs.delete_run_by_conclusion_pattern, 'Unsuccessful:') && 'action_required,cancelled,failure,skipped' || github.event.inputs.delete_run_by_conclusion_pattern) }}
          dry_run: ${{ github.event_name == 'schedule' && false || github.event.inputs.dry_run }}
